DATASET:
  NAME: 'GDRBench'
  NUM_CLASSES: 5
  ROOT: './data/GDRBench' # 你的数据路径

MODEL:
  FPT:
    LPM_PATH: 'google/vit-base-patch16-224' # 确保机器能联网下载，或改为本地绝对路径
    HIGH_RES_SIZE: 512
    LOW_RES_SIZE: 224

INPUT:
  SIZE: 512  # <--- 关键：DataLoader 读取和增强的是 512 的图

BACKBONE: 'FPT' # <--- 触发 model_manager 中的 FPT 分支
ALGORITHM: 'ERM' # <--- 使用基础的 ERM 算法进行训练，但用 FPT 做骨干