DATASET:
  NAME: 'GDRBench'
  NUM_CLASSES: 5
  ROOT: './data/GDRBench'

MODEL:
  FPT:
    LPM_PATH: '/datasets/work/hb-nhmrc-dhcp/work/liu275/DGDR/checkpoints/dinov3_vitb16'
    HIGH_RES_SIZE: 512
    LOW_RES_SIZE: 224
    # [新增] 必须指定要提取特征的层索引 (0-11)
    # 这里的索引对应 ViT-Base 的 12 层 Transformer Block
    LAYERS_TO_EXTRACT: [0, 3, 6, 9]

INPUT:
  SIZE: 512  # DataLoader 读取 512 的图，保证 LPM 有高分输入

BACKBONE: 'FPT'
ALGORITHM: 'ERM' # 或 GDRNet